name: Demo reusable workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  call-build:
    uses: sfdcale/ep-lab-workflows/.github/workflows/build-projects.yml@main
    with:
      affected-plan: '["base","help"]'
