name: Demo action from another repository

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  demo:
    runs-on: ubuntu-24.04
    steps:
      - name: Run the action from another repository
        uses: sfdcale/ep-lab-action@dfb64a91c6672e8588da62e775daa34523c9e6da
        with:
          project: billing
